### ISSUE TITLE
'ppp_pcb' does not name a type; did you mean 'udp_pcb'?

### ISSUE THREAD

**Issue by EckaardKaust** [vshymanskyy/ESP32_PPPoS#4]
Hi all,

Compiling the example code provides the following error: 'ppp_pcb' does not name a type; did you mean 'udp_pcb'?
Running esp32 by Espresso Systems v2.0.6.

Any advice will be appreciated.

**Comment by JoanMCD** [comment]
same here

**Comment by EckaardKaust** [comment]
> same here

Try downgrading the esp32 library to version 2.0.0.

**Comment by JoanMCD** [comment]
Thx for your reply. I use Arduino IDE 1.8.5 with ESP32 2.0.6 from boardmanager.

**Comment by JoanMCD** [comment]
Oh - downgrading !?

**Comment by JoanMCD** [comment]
OK, I have installed ESP32 2.0.0 and it compiles well.
